SEO-175680-extension-UG-page-with-redirects-links
syncfusion-content/extension-docs pull request #123
Opened 2023-09-15 06:23 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.

Regards,
Edith.

2023-09-15 09:46 UTC, Edberg-Vasan commented
rebuild

2023-09-15 09:47 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-extension-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/extension-docs/1360/console)**

2023-09-15 09:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-extension-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/extension-docs/1360/)<br/>**

2023-09-21 12:43 UTC, Yvone-Atieno requested changes
Commented

2023-09-21 12:43 UTC, Yvone-Atieno commented on Extension/Syncfusion-NuGet-Packages/NuGet-Packages.md
> +[NuGet](https://www.nuget.org) can be used to automatically add files and references to your Visual Studio projects. You can use the Syncfusion NuGet packages without installing the Essential Studio
Revert change

2023-09-21 12:43 UTC, Yvone-Atieno commented on Extension/Syncfusion-NuGet-Packages/NuGet-Packages.md
> +N> Starting from v17.1.0.32 (2018 Volume 1), Syncfusion will no longer publish NuGet packages at [nuget.syncfusion.com](https://nuget.syncfusion.com).
Revert change

2023-09-27 08:52 UTC, Edithabich commented on Extension/Syncfusion-NuGet-Packages/NuGet-Packages.md
> +[NuGet](https://www.nuget.org) can be used to automatically add files and references to your Visual Studio projects. You can use the Syncfusion NuGet packages without installing the Essential Studio
resolved

2023-09-27 08:53 UTC, Edithabich commented on Extension/Syncfusion-NuGet-Packages/NuGet-Packages.md
> +N> Starting from v17.1.0.32 (2018 Volume 1), Syncfusion will no longer publish NuGet packages at [nuget.syncfusion.com](https://nuget.syncfusion.com).
resolved

2023-09-27 08:53 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-175680-extension-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/extension-docs/1361/console)**

2023-09-27 08:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-extension-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/extension-docs/1361/console)**

2023-09-27 08:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-extension-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/extension-docs/1361/)<br/>**

2023-09-27 11:36 UTC, Yvone-Atieno requested changes
Commented

2023-09-27 11:36 UTC, Yvone-Atieno commented on Extension/Syncfusion-NuGet-Packages/NuGet-Packages.md
> +N> The Syncfusion NuGet packages are published in public [NuGet.org](https://www.nuget.org) from v16.2.0.46. So, If you need to Install earlier version of 16.2.0.46 Syncfusion NuGet packages, [config
Revert the first link changes

2023-09-27 11:36 UTC, Yvone-Atieno commented on Extension/Syncfusion-NuGet-Packages/NuGet-Packages.md
> +1. Navigate to [nuget.syncfusion.com](https://nuget.syncfusion.com), and select the required platform tab.
Revert this change

2023-09-28 08:14 UTC, Edithabich commented on Extension/Syncfusion-NuGet-Packages/NuGet-Packages.md
> +N> The Syncfusion NuGet packages are published in public [NuGet.org](https://www.nuget.org) from v16.2.0.46. So, If you need to Install earlier version of 16.2.0.46 Syncfusion NuGet packages, [config
resolved

2023-09-28 08:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-extension-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/extension-docs/1362/console)**

2023-09-28 08:15 UTC, Edithabich commented on Extension/Syncfusion-NuGet-Packages/NuGet-Packages.md
> +1. Navigate to [nuget.syncfusion.com](https://nuget.syncfusion.com), and select the required platform tab.
resolved

2023-09-28 08:15 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-extension-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/extension-docs/1362/)<br/>**

2023-09-28 08:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-extension-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/extension-docs/1363/)<br/>**

2023-09-28 08:21 UTC, closed without merging

2023-09-28 08:21 UTC, Edithabich commented
No changes